site_name: Nightscout
theme: flatly
extra_css:
    - css/admonitions.css
markdown_extensions:
    - admonition
    - toc:
        permalink: ⌁

pages:
- What is Nightscout?:
    - 'Introduction': 'index.md'
    - 'How does it work?': 'nightscout/insights.md'
    - 'Uploaders': 'uploader/uploaders.md'
- Install: 'nightscout/new_user.md'
- Configure:
    - 'Configure your Nightscout': 'nightscout/setup_variables.md'
    - 'Setup the uploader': 'uploader/setup.md'
    - 'Nightscout Downloaders': 'nightscout/downloaders.md'
    - 'Nightscout on your watch': 'nightscout/wearable.md'
    - 'Multiple sites administration': 'nightscout/multiadmin.md'
    - 'Close the loop': 'nightscout/close_loop.md'
- Use:
    - 'Discover your site': 'nightscout/discover.md'
    - 'Reports': 'nightscout/reports.md'
    - 'Profile Editor': 'nightscout/profile_editor.md'
    - 'Admin Tools': 'nightscout/admin_tools.md'
- Update:
    - 'Updating your site': 'update/update.md'
    - 'Redeploying': 'update/redeploy.md'
    - 'Attach a new Atlas database': 'update/newdatabase.md'
- Troubleshoot:
    - 'Troubleshooting': 'troubleshoot/troublehoot.md'
    - 'Connection failure': 'troubleshoot/connection_string.md'
    - 'Cleanup': 'troubleshoot/cleanup.md'
