site_name: Nightscout
theme: flatly
extra_css:
    - css/admonitions.css
markdown_extensions:
    - admonition
    - toc:
        permalink: ⌁

pages:
- What is it?:
    - 'Nightscout': 'index.md'
    - 'How does it work?': 'nightscout/insights.md'
    - 'Uploaders': 'uploader/uploaders.md'
- Install: 'nightscout/new_user.md'
- Update:
    - 'Updating your site': 'update/update.md'
    - 'Redeploying': 'update/redeploy.md'
    - 'Migrating to Atlas': 'update/migrate_heroku.md'
    - 'Migrating from Azure': 'update/migrate_azure.md'
- Configure:
    - 'Configure your Nightscout': 'nightscout/setup_variables.md'
    - 'Setup the uploader': 'uploader/setup.md'
    - 'Close the loop': 'nightscout/close_loop.md'
- Use:
    - 'Reports': 'nightscout/reports.md'
    - 'IF This Then That': 'nightscout/ifttt.md'
    - 'Pebble': 'nightscout/pebble.md'
    - 'Remote Notifications': 'nightscout/pushover.md'
- Troubleshoot:
    - 'Troubleshooting': 'troubleshoot/troublehoot.md'
    - 'Nightscout stopped working': 'nightscout/mlab_cleanup.md'
